apiVersion: v1
kind: Service
metadata:
  name: alfred-ai
  labels:
    app: alfred-ai
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    - port: 8081
      targetPort: gateway
      protocol: TCP
      name: gateway
  selector:
    app: alfred-ai
